from pathlib import Path
p=Path('src/features/fuel/FuelManagement.tsx')
s=p.read_text()
s=s.replace('import { Download, FileSpreadsheet, Fuel, Plus, RefreshCcw, Search, Trash2, Upload } from "lucide-react";','import { Download, FileSpreadsheet, Fuel, Plus, RefreshCcw, Search, Settings2, Trash2, Upload } from "lucide-react";')
old='''        <button type="button" onClick={() => fileInput.current?.click()}><Upload size={16} /> 명세서 가져오기</button>\n        <button type="button" onClick={exportStatementExcel}><Download size={16} /> 명세서 엑셀</button>\n        <button type="button" onClick={exportGeneralExcel}><Download size={16} /> 목록 엑셀</button>\n        <button type="button" onClick={() => setManualOpen((value) => !value)}><Plus size={16} /> 직접 입력</button>\n        <button type="button" onClick={() => void load()} disabled={loading}><RefreshCcw size={16} /> 새로고침</button>'''
new='''        <button type="button" onClick={() => fileInput.current?.click()}><Upload size={16} /> 명세서 가져오기</button>\n        <button type="button" onClick={() => setManualOpen((value) => !value)}><Plus size={16} /> 직접 입력</button>\n        <button type="button" className={view === "basics" ? "fuel-basics-action is-active" : "fuel-basics-action"} onClick={() => { setView((current) => current === "basics" ? "records" : "basics"); setDetailTarget(null); }}><Settings2 size={16} /> {view === "basics" ? "주유내역 보기" : "기초등록"}</button>\n        <span className="fuel-action-divider" aria-hidden="true" />\n        <button type="button" onClick={exportStatementExcel}><Download size={16} /> 명세서 엑셀</button>\n        <button type="button" onClick={exportGeneralExcel}><Download size={16} /> 목록 엑셀</button>\n        <button type="button" onClick={() => void load()} disabled={loading}><RefreshCcw size={16} /> 새로고침</button>'''
if old not in s: raise SystemExit('header actions anchor not found')
s=s.replace(old,new,1)
old='''    <div className="fuel-toolbar">\n      <label><span>조회월</span><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label>\n      <label><span>현장</span><select value={site} onChange={(event) => setSite(event.target.value)}><option value="">전체 현장</option>{sites.map((name) => <option key={name}>{name}</option>)}</select></label>\n      <label><span>유종</span><select value={product} onChange={(event) => setProduct(event.target.value)}><option value="">전체 유종</option>{products.map((name) => <option key={name}>{name}</option>)}</select></label>\n      <label className="fuel-search"><span>차량/장비</span><div><Search size={15} /><input value={vehicleSearch} onChange={(event) => setVehicleSearch(event.target.value)} placeholder="차량번호 검색" /></div></label>\n    </div>\n\n    <div className="fuel-kpis">\n      <article><span>총 유류비</span><strong>{money(totals.total)}<small>원</small></strong></article>\n      <article><span>전체 수량</span><strong>{number(totals.quantity)}<small>L</small></strong></article>\n      <article><span>경유</span><strong>{number(totals.diesel)}<small>L</small></strong></article>\n      <article><span>요소수</span><strong>{number(totals.urea)}<small>L</small></strong></article>\n      <article><span>주유 횟수</span><strong>{number(totals.count)}<small>회</small></strong></article>\n    </div>\n\n    <nav className="fuel-tabs" aria-label="유류관리 보기">\n      <button type="button" aria-pressed={view === "records"} onClick={() => { setView("records"); setDetailTarget(null); }}>주유내역</button>\n      <button type="button" aria-pressed={view === "vehicle"} onClick={() => { setView("vehicle"); setDetailTarget(null); }}>차량·장비별</button>\n      <button type="button" aria-pressed={view === "site"} onClick={() => { setView("site"); setDetailTarget(null); }}>현장별</button>\n      <button type="button" aria-pressed={view === "station"} onClick={() => { setView("station"); setDetailTarget(null); }}>주유소별</button>\n      <button type="button" aria-pressed={view === "basics"} onClick={() => { setView("basics"); setDetailTarget(null); }}>기초등록</button>\n    </nav>'''
new='''    {view !== "basics" && <>\n      <div className="fuel-toolbar">\n        <label><span>조회월</span><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label>\n        <label><span>현장</span><select value={site} onChange={(event) => setSite(event.target.value)}><option value="">전체 현장</option>{sites.map((name) => <option key={name}>{name}</option>)}</select></label>\n        <label><span>유종</span><select value={product} onChange={(event) => setProduct(event.target.value)}><option value="">전체 유종</option>{products.map((name) => <option key={name}>{name}</option>)}</select></label>\n        <label className="fuel-search"><span>차량/장비</span><div><Search size={15} /><input value={vehicleSearch} onChange={(event) => setVehicleSearch(event.target.value)} placeholder="차량번호 검색" /></div></label>\n      </div>\n\n      <div className="fuel-kpis">\n        <article><span>총 유류비</span><strong>{money(totals.total)}<small>원</small></strong></article>\n        <article><span>전체 수량</span><strong>{number(totals.quantity)}<small>L</small></strong></article>\n        <article><span>경유</span><strong>{number(totals.diesel)}<small>L</small></strong></article>\n        <article><span>요소수</span><strong>{number(totals.urea)}<small>L</small></strong></article>\n        <article><span>주유 횟수</span><strong>{number(totals.count)}<small>회</small></strong></article>\n      </div>\n\n      <nav className="fuel-tabs" aria-label="유류관리 보기">\n        <button type="button" aria-pressed={view === "records"} onClick={() => { setView("records"); setDetailTarget(null); }}>주유내역</button>\n        <button type="button" aria-pressed={view === "vehicle"} onClick={() => { setView("vehicle"); setDetailTarget(null); }}>차량·장비별</button>\n        <button type="button" aria-pressed={view === "site"} onClick={() => { setView("site"); setDetailTarget(null); }}>현장별</button>\n        <button type="button" aria-pressed={view === "station"} onClick={() => { setView("station"); setDetailTarget(null); }}>주유소별</button>\n      </nav>\n    </>}'''
if old not in s: raise SystemExit('toolbar/tabs anchor not found')
s=s.replace(old,new,1)
p.write_text(s)

css=Path('src/features/fuel/fuelManagement.css')
cs=css.read_text()
cs += '''\n.fuel-head-actions .fuel-basics-action{border-color:#c7d7e8;background:#f8fbff;color:#1e3a5f}.fuel-head-actions .fuel-basics-action:hover{background:#eef6ff}.fuel-head-actions .fuel-basics-action.is-active{border-color:#2563eb;background:#eff6ff;color:#1d4ed8}.fuel-action-divider{width:1px;height:32px;background:#dbe2ea;align-self:center;margin:0 2px}.fuel-master-grid{margin-top:2px}@media(max-width:760px){.fuel-action-divider{display:none}.fuel-head-actions{grid-template-columns:repeat(2,minmax(0,1fr))}.fuel-head-actions .fuel-basics-action{grid-column:span 2}.fuel-tabs{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));width:100%}.fuel-tabs button{min-width:0}}@media(max-width:520px){.fuel-tabs{grid-template-columns:repeat(2,minmax(0,1fr))}}\n'''
css.write_text(cs)
